### ISSUE TITLE
Suggestion of lightning parametrization

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/WRF-Chem-R2SMH#10]
# Suggestion description

Describe the suggestion in detail here:
- **branch**: lightning
- @qdzhu is working on lightning parametrization and the method is based on CAPE and PRATEC. 
- Recently, **a new parametrization** is developed/implemented by Paul Field (doi: 10.1029/2018jd029295). This mathod takes `the upward flux of ice` and `the amounts of graupe in the cloud` into account. These elements are directly related to lightning. Declan Finney has mentioned that in his paper before (https://doi.org/10.1038/s41558-018-0072-6).
- If you're interested in it, you can check it out. Hope this can help you.

**Comment by qdzhu** [comment]
Thanks for your suggestion.
This branch is one of my working branches, which means it is unpublished yet and is subject to any changes. Please go back to the **master** branch, it is the only branch intended to open to public.
Thank you so much.

**Comment by zxdawn** [comment]
@qdzhu You're welcome. Hope these can fix the overestimation of flash density in the southeast US~
