### ISSUE TITLE
Definition of LNOXA and others

### ISSUE THREAD

**Issue by zxdawn** [CohenBerkeleyLab/WRF-Chem-R2SMH#11]
What's the definition of `LNOXA`, `LNOXHNO3`, `LNOXPAN`, and `LNOXB` in output?
For example, `LNOXHNO3`: https://github.com/CohenBerkeleyLab/WRF-Chem-R2SMH/blob/52309055b848a5503f96d2adb84ba9c99feb31ec/chem/KPP/mechanisms/r2smh/r2smh.eqn_LNOX#L55
What's the exact meaning of this reaction?

**Comment by joshua-laughner** [comment]
These are diagnostic species that give various loss rates.

LNOXA = loss of NOx to alkyl nitrates
LNOXHNO3 = loss of NOx to nitric acid
LNOXPAN = loss of NOx to acetyl peroxy nitrates
LNOXB = loss of NOx by reaction of NO3 with organic species

If you search the [equation file](https://github.com/CohenBerkeleyLab/WRF-Chem-R2SMH/blob/master/chem/KPP/mechanisms/r2smh/r2smh.eqn) you can see exactly which reactions "produce" these diagnostics.
